### PR TITLE
DA-238+DA-246: Fix and improve user deleting

### PR DESCRIPTION
**Pull request by JeannedArk**
Deleting a user did not remove all dependencies e.g. watching users and
project dependencies. It was also not very efficient therefore #238 is
involved.

### CODE REVIEW

**Comment by stgrue** [comment]
When deleting an annotator, the projects they were assigned to do not appear in the project explorer anymore. However, they are also not properly deleted, since trying to add another project with the same name results in an error.
Opening the project explorer in this state gives the following error:
```
angular.js:12722 rootController: States and users length differs
(anonymous function) @ angular.js:12722
(anonymous function) @ angular.js:9490
(anonymous function) @ angular.js:14999
$eval @ angular.js:16251
$digest @ angular.js:16069
$apply @ angular.js:16359
g @ angular.js:10791
R @ angular.js:10989
v.onload @ angular.js:10930
```

**Comment by stgrue** [comment]
Nevermind my previous comment, that error appeared only because I was logged in twice in two different browser instances.

**Comment by stgrue** [comment]
My confusion knows no bouds. The error was actually real, I was just on the wrong branch. So, to reiterate:
When you delete a user, the project they were assigned to disappears from the project explorer. However, it is not actually deleted, since you cannot add a project of the same name. Additionally, opening the project explorer in this state gives the following error:

```
rootController: States and users length differs
(anonymous function) @ angular.js:12722
(anonymous function) @ angular.js:9490
(anonymous function) @ angular.js:14999
$eval @ angular.js:16251
$digest @ angular.js:16069
$apply @ angular.js:16359
g @ angular.js:10791
R @ angular.js:10989
v.onload @ angular.js:10930
```

**Comment by JeannedArk** [comment]
Updated

**Comment by judembo** [comment]
If a project manager has created some schemes and the project manager is later deleted, the schemes (and projects using those schemes) remain, but the creator_id field for the scheme is then empty. Maybe it could be changed to the admin's id? I don't know when this reference is even needed - if it's not, the branch is ready to merge

**Comment by JeannedArk** [comment]
This is by purpose.

**Pull request merged**
