### PR TITLE
DA-15: Insert timeline and visualization scheme options

### PR DESCRIPTION
**Pull request by JeannedArk**

### CODE REVIEW

**Comment by JeannedArk** [comment]
@stgrue @judembo Please test carefully. These are fundamental changes. Espescially play around with the scheme builder, switching between states and the timeline view.

Note: This will be merged into the development branch. This will be our base branch, then we will rebase master with development branch, if the feedback is positive.

Edit: Drop all tables except the users table.

**Comment by JeannedArk** [comment]
- Upload from existing
- switching from timeline to graph when creating a label
- annotation type/ span tybe

**Comment by JeannedArk** [comment]
Pull request updated. Upload from existing and switching from timeline to graph when defining a linklabel but not adding, should be fixed now. @judembo @stgrue

**Comment by judembo** [comment]
Loading an existing scheme still doesn't work properly for the link labels, because in sendScheme() a list for the positioning option is created, but when loading the schemes again the link sets (with the lists) are simply kept.

**Comment by JeannedArk** [comment]
Should be fixed now, pls test it again.

**Comment by stgrue** [comment]
Something might still be wrong with uploading a scheme from a file. I created multiple schemes in the scheme builder, copied the JSON onto my hard drive and tried to import them again, and got the following error in both cases:

```
Selected file does not contain a valid annotation
scheme. Reason: TypeError: Cannot read
property  'length' of null
```

**Pull request merged**
