### PR TITLE
DA-40: Improve users page including sorting users by email and reset …

### PR DESCRIPTION
**Pull request by JeannedArk**
…password feature

Users will be sent ordered by their email. The logged time will be formatted.
Instead of submitting a new password of other users, a reset button was created
which generates a random password, replaces the current password and sends it
to the email.

### CODE REVIEW

**Comment by annefried** [comment]
Sending the email doesn't work:
 StandardWrapperValve[Jersey Web Application]: Servlet.service() for servlet Jersey Web Application threw exception
javax.naming.NameNotFoundException: mail

**Comment by annefried** [comment]
Should we simply go back to letting the admin / project manager set a new password (for now)?

**Comment by JeannedArk** [comment]
The E-Mail functionality has to be configured with a simple command. The command is in the EmailProvider class.

**Comment by JeannedArk** [comment]
Let's work it out after the ACL and test it properly on the VM

**Comment by annefried** [comment]
agree with @JeannedArk -- this also depends on the infrastructure and will need to an option that admins can disable during deployment

**Comment by annefried** [comment]
Merging this PR because of the non-email-functionality that it contains.

**Pull request merged**
