### PR TITLE
DA-159: Drastically increase performance of rendering

### PR DESCRIPTION
**Pull request by NicklasLinz**
Accesses to properties of svg elements have been bundled into one call.
This allows the browser to combine layout reflows, which increases performance.
Pixel values used in svg's are now rounded, to improve performance.
The whole text is no longer rendered when loading a document.

### CODE REVIEW

**Comment by JeannedArk** [comment]
I will test it and please test @cbocionek asap
It would be a good "exercise" if @stgrue and @judembo could test it before tomorrow meeting

**Comment by JeannedArk** [comment]
Performance is amazing compared to the state before. There is a problem with selecting the next annotation via shortcuts. Displaying links across the documents seems to work. Code style is improvable.

**Comment by cbocionek** [comment]
Can confirm that rendering is noticeably faster. A bit jumpy, however, for lack of a better word.

**Comment by JeannedArk** [comment]
Why has this been merged when there is still a bug?

**Comment by cbocionek** [comment]
Sorry, that was my misjudgement.

**Pull request merged**
