### PR TITLE
DA-68: Validate the annotation types when uploading a scheme

### PR DESCRIPTION
**Pull request by JeannedArk**
Make further checks on the uploaded scheme when annotation types don't match.

### CODE REVIEW

**Comment by annefried** [comment]
Upload only worked when the Json with the targets was correct. If an invalid target type is given, a server error happens. If Json is invalid, no appropriate message is given. Please check @JeannedArk

**Comment by JeannedArk** [comment]
Added the target file validation. The text file "iraqExotic.txt" and the corresponding target file "iraqExotic.json" should provoke the error message.

**Comment by annefried** [comment]
Slightly adapted error messages (when uploading XML it should not say 'invalid json'). We should display the error message for a bit longer in the future.

**Comment by JeannedArk** [comment]
Good point. You do not have to accept the merge request if it is not perfect/ something to work on :)

**Pull request merged**
