### PR TITLE
DA-209+DA-148: Rename discanno to swan and add base to reimport

### PR DESCRIPTION
**Pull request by JeannedArk**
The packages were renamed discanno to swan and refactored. This
deals with #209 because for #148 the package structure was
refactored. For #148 the scheme will be exported additionally.

### CODE REVIEW

**Comment by JeannedArk** [comment]
Note: The full reimport functionality will follow but this would have been too much.

**Comment by stgrue** [comment]
Everything seems to work well, however running `grep '[Dd]isc[Aa]nno' -R` on the /src/ subfolder shows that there are still some pieces of code referring to DiscAnno. From a quick glance most of those do not seem terribly important, though.

**Comment by JeannedArk** [comment]
The only relevant file I see is glassfish-resources.xml. We can change it now but then everybody has to be notfied that the database is now called swan and not discanno.
Edit: There are some more, more or less relevant.

**Comment by JeannedArk** [comment]
Updated @stgrue

**Pull request merged**
